// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/report"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ReportCreate is the builder for creating a Report entity.
type ReportCreate struct {
	config
	mutation *ReportMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *ReportCreate) SetUserID(v int64) *ReportCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ReportCreate) SetType(v string) *ReportCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *ReportCreate) SetPeriodStart(v time.Time) *ReportCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetPeriodEnd sets the "period_end" field.
func (_c *ReportCreate) SetPeriodEnd(v time.Time) *ReportCreate {
	_c.mutation.SetPeriodEnd(v)
	return _c
}

// SetStats sets the "stats" field.
func (_c *ReportCreate) SetStats(v domain.ReportStats) *ReportCreate {
	_c.mutation.SetStats(v)
	return _c
}

// SetAiSummary sets the "ai_summary" field.
func (_c *ReportCreate) SetAiSummary(v string) *ReportCreate {
	_c.mutation.SetAiSummary(v)
	return _c
}

// SetNillableAiSummary sets the "ai_summary" field if the given value is not nil.
func (_c *ReportCreate) SetNillableAiSummary(v *string) *ReportCreate {
	if v != nil {
		_c.SetAiSummary(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReportCreate) SetStatus(v string) *ReportCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReportCreate) SetNillableStatus(v *string) *ReportCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *ReportCreate) SetError(v string) *ReportCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *ReportCreate) SetNillableError(v *string) *ReportCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetPushedAt sets the "pushed_at" field.
func (_c *ReportCreate) SetPushedAt(v time.Time) *ReportCreate {
	_c.mutation.SetPushedAt(v)
	return _c
}

// SetNillablePushedAt sets the "pushed_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillablePushedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetPushedAt(*v)
	}
	return _c
}

// SetLastPushError sets the "last_push_error" field.
func (_c *ReportCreate) SetLastPushError(v string) *ReportCreate {
	_c.mutation.SetLastPushError(v)
	return _c
}

// SetNillableLastPushError sets the "last_push_error" field if the given value is not nil.
func (_c *ReportCreate) SetNillableLastPushError(v *string) *ReportCreate {
	if v != nil {
		_c.SetLastPushError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportCreate) SetCreatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableCreatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReportCreate) SetUpdatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableUpdatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ReportMutation object of the builder.
func (_c *ReportCreate) Mutation() *ReportMutation {
	return _c.mutation
}

// Save creates the Report in the database.
func (_c *ReportCreate) Save(ctx context.Context) (*Report, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportCreate) SaveX(ctx context.Context) *Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReportCreate) defaults() {
	if _, ok := _c.mutation.AiSummary(); !ok {
		v := report.DefaultAiSummary
		_c.mutation.SetAiSummary(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := report.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := report.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.LastPushError(); !ok {
		v := report.DefaultLastPushError
		_c.mutation.SetLastPushError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := report.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := report.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Report.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Report.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := report.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Report.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "Report.period_start"`)}
	}
	if _, ok := _c.mutation.PeriodEnd(); !ok {
		return &ValidationError{Name: "period_end", err: errors.New(`ent: missing required field "Report.period_end"`)}
	}
	if _, ok := _c.mutation.Stats(); !ok {
		return &ValidationError{Name: "stats", err: errors.New(`ent: missing required field "Report.stats"`)}
	}
	if _, ok := _c.mutation.AiSummary(); !ok {
		return &ValidationError{Name: "ai_summary", err: errors.New(`ent: missing required field "Report.ai_summary"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Report.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "Report.error"`)}
	}
	if _, ok := _c.mutation.LastPushError(); !ok {
		return &ValidationError{Name: "last_push_error", err: errors.New(`ent: missing required field "Report.last_push_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Report.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Report.updated_at"`)}
	}
	return nil
}

func (_c *ReportCreate) sqlSave(ctx context.Context) (*Report, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportCreate) createSpec() (*Report, *sqlgraph.CreateSpec) {
	var (
		_node = &Report{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(report.Table, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(report.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(report.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(report.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.PeriodEnd(); ok {
		_spec.SetField(report.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = value
	}
	if value, ok := _c.mutation.Stats(); ok {
		_spec.SetField(report.FieldStats, field.TypeJSON, value)
		_node.Stats = value
	}
	if value, ok := _c.mutation.AiSummary(); ok {
		_spec.SetField(report.FieldAiSummary, field.TypeString, value)
		_node.AiSummary = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(report.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.PushedAt(); ok {
		_spec.SetField(report.FieldPushedAt, field.TypeTime, value)
		_node.PushedAt = &value
	}
	if value, ok := _c.mutation.LastPushError(); ok {
		_spec.SetField(report.FieldLastPushError, field.TypeString, value)
		_node.LastPushError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(report.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Report.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReportUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReportCreate) OnConflict(opts ...sql.ConflictOption) *ReportUpsertOne {
	_c.conflict = opts
	return &ReportUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReportCreate) OnConflictColumns(columns ...string) *ReportUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReportUpsertOne{
		create: _c,
	}
}

type (
	// ReportUpsertOne is the builder for "upsert"-ing
	//  one Report node.
	ReportUpsertOne struct {
		create *ReportCreate
	}

	// ReportUpsert is the "OnConflict" setter.
	ReportUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *ReportUpsert) SetUserID(v int64) *ReportUpsert {
	u.Set(report.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReportUpsert) UpdateUserID() *ReportUpsert {
	u.SetExcluded(report.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ReportUpsert) AddUserID(v int64) *ReportUpsert {
	u.Add(report.FieldUserID, v)
	return u
}

// SetType sets the "type" field.
func (u *ReportUpsert) SetType(v string) *ReportUpsert {
	u.Set(report.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ReportUpsert) UpdateType() *ReportUpsert {
	u.SetExcluded(report.FieldType)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *ReportUpsert) SetPeriodStart(v time.Time) *ReportUpsert {
	u.Set(report.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ReportUpsert) UpdatePeriodStart() *ReportUpsert {
	u.SetExcluded(report.FieldPeriodStart)
	return u
}

// SetPeriodEnd sets the "period_end" field.
func (u *ReportUpsert) SetPeriodEnd(v time.Time) *ReportUpsert {
	u.Set(report.FieldPeriodEnd, v)
	return u
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ReportUpsert) UpdatePeriodEnd() *ReportUpsert {
	u.SetExcluded(report.FieldPeriodEnd)
	return u
}

// SetStats sets the "stats" field.
func (u *ReportUpsert) SetStats(v domain.ReportStats) *ReportUpsert {
	u.Set(report.FieldStats, v)
	return u
}

// UpdateStats sets the "stats" field to the value that was provided on create.
func (u *ReportUpsert) UpdateStats() *ReportUpsert {
	u.SetExcluded(report.FieldStats)
	return u
}

// SetAiSummary sets the "ai_summary" field.
func (u *ReportUpsert) SetAiSummary(v string) *ReportUpsert {
	u.Set(report.FieldAiSummary, v)
	return u
}

// UpdateAiSummary sets the "ai_summary" field to the value that was provided on create.
func (u *ReportUpsert) UpdateAiSummary() *ReportUpsert {
	u.SetExcluded(report.FieldAiSummary)
	return u
}

// SetStatus sets the "status" field.
func (u *ReportUpsert) SetStatus(v string) *ReportUpsert {
	u.Set(report.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReportUpsert) UpdateStatus() *ReportUpsert {
	u.SetExcluded(report.FieldStatus)
	return u
}

// SetError sets the "error" field.
func (u *ReportUpsert) SetError(v string) *ReportUpsert {
	u.Set(report.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ReportUpsert) UpdateError() *ReportUpsert {
	u.SetExcluded(report.FieldError)
	return u
}

// SetPushedAt sets the "pushed_at" field.
func (u *ReportUpsert) SetPushedAt(v time.Time) *ReportUpsert {
	u.Set(report.FieldPushedAt, v)
	return u
}

// UpdatePushedAt sets the "pushed_at" field to the value that was provided on create.
func (u *ReportUpsert) UpdatePushedAt() *ReportUpsert {
	u.SetExcluded(report.FieldPushedAt)
	return u
}

// ClearPushedAt clears the value of the "pushed_at" field.
func (u *ReportUpsert) ClearPushedAt() *ReportUpsert {
	u.SetNull(report.FieldPushedAt)
	return u
}

// SetLastPushError sets the "last_push_error" field.
func (u *ReportUpsert) SetLastPushError(v string) *ReportUpsert {
	u.Set(report.FieldLastPushError, v)
	return u
}

// UpdateLastPushError sets the "last_push_error" field to the value that was provided on create.
func (u *ReportUpsert) UpdateLastPushError() *ReportUpsert {
	u.SetExcluded(report.FieldLastPushError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReportUpsert) SetUpdatedAt(v time.Time) *ReportUpsert {
	u.Set(report.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReportUpsert) UpdateUpdatedAt() *ReportUpsert {
	u.SetExcluded(report.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReportUpsertOne) UpdateNewValues() *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(report.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Report.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReportUpsertOne) Ignore() *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReportUpsertOne) DoNothing() *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReportCreate.OnConflict
// documentation for more info.
func (u *ReportUpsertOne) Update(set func(*ReportUpsert)) *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ReportUpsertOne) SetUserID(v int64) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ReportUpsertOne) AddUserID(v int64) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateUserID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *ReportUpsertOne) SetType(v string) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateType() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateType()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *ReportUpsertOne) SetPeriodStart(v time.Time) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdatePeriodStart() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *ReportUpsertOne) SetPeriodEnd(v time.Time) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdatePeriodEnd() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetStats sets the "stats" field.
func (u *ReportUpsertOne) SetStats(v domain.ReportStats) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetStats(v)
	})
}

// UpdateStats sets the "stats" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateStats() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateStats()
	})
}

// SetAiSummary sets the "ai_summary" field.
func (u *ReportUpsertOne) SetAiSummary(v string) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetAiSummary(v)
	})
}

// UpdateAiSummary sets the "ai_summary" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateAiSummary() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateAiSummary()
	})
}

// SetStatus sets the "status" field.
func (u *ReportUpsertOne) SetStatus(v string) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateStatus() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *ReportUpsertOne) SetError(v string) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateError() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateError()
	})
}

// SetPushedAt sets the "pushed_at" field.
func (u *ReportUpsertOne) SetPushedAt(v time.Time) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetPushedAt(v)
	})
}

// UpdatePushedAt sets the "pushed_at" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdatePushedAt() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdatePushedAt()
	})
}

// ClearPushedAt clears the value of the "pushed_at" field.
func (u *ReportUpsertOne) ClearPushedAt() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.ClearPushedAt()
	})
}

// SetLastPushError sets the "last_push_error" field.
func (u *ReportUpsertOne) SetLastPushError(v string) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetLastPushError(v)
	})
}

// UpdateLastPushError sets the "last_push_error" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateLastPushError() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateLastPushError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReportUpsertOne) SetUpdatedAt(v time.Time) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateUpdatedAt() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReportUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReportCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReportUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReportUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReportUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReportCreateBulk is the builder for creating many Report entities in bulk.
type ReportCreateBulk struct {
	config
	err      error
	builders []*ReportCreate
	conflict []sql.ConflictOption
}

// Save creates the Report entities in the database.
func (_c *ReportCreateBulk) Save(ctx context.Context) ([]*Report, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Report, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportCreateBulk) SaveX(ctx context.Context) []*Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Report.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReportUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReportCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReportUpsertBulk {
	_c.conflict = opts
	return &ReportUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReportCreateBulk) OnConflictColumns(columns ...string) *ReportUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReportUpsertBulk{
		create: _c,
	}
}

// ReportUpsertBulk is the builder for "upsert"-ing
// a bulk of Report nodes.
type ReportUpsertBulk struct {
	create *ReportCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReportUpsertBulk) UpdateNewValues() *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(report.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReportUpsertBulk) Ignore() *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReportUpsertBulk) DoNothing() *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReportCreateBulk.OnConflict
// documentation for more info.
func (u *ReportUpsertBulk) Update(set func(*ReportUpsert)) *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ReportUpsertBulk) SetUserID(v int64) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ReportUpsertBulk) AddUserID(v int64) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateUserID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *ReportUpsertBulk) SetType(v string) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateType() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateType()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *ReportUpsertBulk) SetPeriodStart(v time.Time) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdatePeriodStart() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *ReportUpsertBulk) SetPeriodEnd(v time.Time) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdatePeriodEnd() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetStats sets the "stats" field.
func (u *ReportUpsertBulk) SetStats(v domain.ReportStats) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetStats(v)
	})
}

// UpdateStats sets the "stats" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateStats() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateStats()
	})
}

// SetAiSummary sets the "ai_summary" field.
func (u *ReportUpsertBulk) SetAiSummary(v string) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetAiSummary(v)
	})
}

// UpdateAiSummary sets the "ai_summary" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateAiSummary() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateAiSummary()
	})
}

// SetStatus sets the "status" field.
func (u *ReportUpsertBulk) SetStatus(v string) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateStatus() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *ReportUpsertBulk) SetError(v string) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateError() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateError()
	})
}

// SetPushedAt sets the "pushed_at" field.
func (u *ReportUpsertBulk) SetPushedAt(v time.Time) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetPushedAt(v)
	})
}

// UpdatePushedAt sets the "pushed_at" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdatePushedAt() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdatePushedAt()
	})
}

// ClearPushedAt clears the value of the "pushed_at" field.
func (u *ReportUpsertBulk) ClearPushedAt() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.ClearPushedAt()
	})
}

// SetLastPushError sets the "last_push_error" field.
func (u *ReportUpsertBulk) SetLastPushError(v string) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetLastPushError(v)
	})
}

// UpdateLastPushError sets the "last_push_error" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateLastPushError() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateLastPushError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReportUpsertBulk) SetUpdatedAt(v time.Time) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateUpdatedAt() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReportUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReportCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReportCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReportUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
