// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/report"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ReportUpdate is the builder for updating Report entities.
type ReportUpdate struct {
	config
	hooks    []Hook
	mutation *ReportMutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdate) Where(ps ...predicate.Report) *ReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ReportUpdate) SetUserID(v int64) *ReportUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableUserID(v *int64) *ReportUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ReportUpdate) AddUserID(v int64) *ReportUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ReportUpdate) SetType(v string) *ReportUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableType(v *string) *ReportUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ReportUpdate) SetPeriodStart(v time.Time) *ReportUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ReportUpdate) SetNillablePeriodStart(v *time.Time) *ReportUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ReportUpdate) SetPeriodEnd(v time.Time) *ReportUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ReportUpdate) SetNillablePeriodEnd(v *time.Time) *ReportUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetStats sets the "stats" field.
func (_u *ReportUpdate) SetStats(v domain.ReportStats) *ReportUpdate {
	_u.mutation.SetStats(v)
	return _u
}

// SetNillableStats sets the "stats" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableStats(v *domain.ReportStats) *ReportUpdate {
	if v != nil {
		_u.SetStats(*v)
	}
	return _u
}

// SetAiSummary sets the "ai_summary" field.
func (_u *ReportUpdate) SetAiSummary(v string) *ReportUpdate {
	_u.mutation.SetAiSummary(v)
	return _u
}

// SetNillableAiSummary sets the "ai_summary" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableAiSummary(v *string) *ReportUpdate {
	if v != nil {
		_u.SetAiSummary(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportUpdate) SetStatus(v string) *ReportUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableStatus(v *string) *ReportUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *ReportUpdate) SetError(v string) *ReportUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableError(v *string) *ReportUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetPushedAt sets the "pushed_at" field.
func (_u *ReportUpdate) SetPushedAt(v time.Time) *ReportUpdate {
	_u.mutation.SetPushedAt(v)
	return _u
}

// SetNillablePushedAt sets the "pushed_at" field if the given value is not nil.
func (_u *ReportUpdate) SetNillablePushedAt(v *time.Time) *ReportUpdate {
	if v != nil {
		_u.SetPushedAt(*v)
	}
	return _u
}

// ClearPushedAt clears the value of the "pushed_at" field.
func (_u *ReportUpdate) ClearPushedAt() *ReportUpdate {
	_u.mutation.ClearPushedAt()
	return _u
}

// SetLastPushError sets the "last_push_error" field.
func (_u *ReportUpdate) SetLastPushError(v string) *ReportUpdate {
	_u.mutation.SetLastPushError(v)
	return _u
}

// SetNillableLastPushError sets the "last_push_error" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableLastPushError(v *string) *ReportUpdate {
	if v != nil {
		_u.SetLastPushError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportUpdate) SetUpdatedAt(v time.Time) *ReportUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdate) Mutation() *ReportMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReportUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := report.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := report.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Report.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(report.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(report.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(report.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(report.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(report.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Stats(); ok {
		_spec.SetField(report.FieldStats, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AiSummary(); ok {
		_spec.SetField(report.FieldAiSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(report.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.PushedAt(); ok {
		_spec.SetField(report.FieldPushedAt, field.TypeTime, value)
	}
	if _u.mutation.PushedAtCleared() {
		_spec.ClearField(report.FieldPushedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPushError(); ok {
		_spec.SetField(report.FieldLastPushError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReportUpdateOne is the builder for updating a single Report entity.
type ReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportMutation
}

// SetUserID sets the "user_id" field.
func (_u *ReportUpdateOne) SetUserID(v int64) *ReportUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableUserID(v *int64) *ReportUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ReportUpdateOne) AddUserID(v int64) *ReportUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ReportUpdateOne) SetType(v string) *ReportUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableType(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ReportUpdateOne) SetPeriodStart(v time.Time) *ReportUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillablePeriodStart(v *time.Time) *ReportUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ReportUpdateOne) SetPeriodEnd(v time.Time) *ReportUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillablePeriodEnd(v *time.Time) *ReportUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetStats sets the "stats" field.
func (_u *ReportUpdateOne) SetStats(v domain.ReportStats) *ReportUpdateOne {
	_u.mutation.SetStats(v)
	return _u
}

// SetNillableStats sets the "stats" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableStats(v *domain.ReportStats) *ReportUpdateOne {
	if v != nil {
		_u.SetStats(*v)
	}
	return _u
}

// SetAiSummary sets the "ai_summary" field.
func (_u *ReportUpdateOne) SetAiSummary(v string) *ReportUpdateOne {
	_u.mutation.SetAiSummary(v)
	return _u
}

// SetNillableAiSummary sets the "ai_summary" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableAiSummary(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetAiSummary(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportUpdateOne) SetStatus(v string) *ReportUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableStatus(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *ReportUpdateOne) SetError(v string) *ReportUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableError(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetPushedAt sets the "pushed_at" field.
func (_u *ReportUpdateOne) SetPushedAt(v time.Time) *ReportUpdateOne {
	_u.mutation.SetPushedAt(v)
	return _u
}

// SetNillablePushedAt sets the "pushed_at" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillablePushedAt(v *time.Time) *ReportUpdateOne {
	if v != nil {
		_u.SetPushedAt(*v)
	}
	return _u
}

// ClearPushedAt clears the value of the "pushed_at" field.
func (_u *ReportUpdateOne) ClearPushedAt() *ReportUpdateOne {
	_u.mutation.ClearPushedAt()
	return _u
}

// SetLastPushError sets the "last_push_error" field.
func (_u *ReportUpdateOne) SetLastPushError(v string) *ReportUpdateOne {
	_u.mutation.SetLastPushError(v)
	return _u
}

// SetNillableLastPushError sets the "last_push_error" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableLastPushError(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetLastPushError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportUpdateOne) SetUpdatedAt(v time.Time) *ReportUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdateOne) Mutation() *ReportMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdateOne) Where(ps ...predicate.Report) *ReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReportUpdateOne) Select(field string, fields ...string) *ReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Report entity.
func (_u *ReportUpdateOne) Save(ctx context.Context) (*Report, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdateOne) SaveX(ctx context.Context) *Report {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := report.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := report.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Report.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportUpdateOne) sqlSave(ctx context.Context) (_node *Report, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Report.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, report.FieldID)
		for _, f := range fields {
			if !report.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != report.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(report.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(report.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(report.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(report.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(report.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Stats(); ok {
		_spec.SetField(report.FieldStats, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AiSummary(); ok {
		_spec.SetField(report.FieldAiSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(report.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.PushedAt(); ok {
		_spec.SetField(report.FieldPushedAt, field.TypeTime, value)
	}
	if _u.mutation.PushedAtCleared() {
		_spec.ClearField(report.FieldPushedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPushError(); ok {
		_spec.SetField(report.FieldLastPushError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Report{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
