// Code generated by ent, DO NOT EDIT.

package report

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUserID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldType, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldPeriodEnd, v))
}

// AiSummary applies equality check predicate on the "ai_summary" field. It's identical to AiSummaryEQ.
func AiSummary(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldAiSummary, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldStatus, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldError, v))
}

// PushedAt applies equality check predicate on the "pushed_at" field. It's identical to PushedAtEQ.
func PushedAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldPushedAt, v))
}

// LastPushError applies equality check predicate on the "last_push_error" field. It's identical to LastPushErrorEQ.
func LastPushError(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldLastPushError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldType, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldPeriodEnd, v))
}

// AiSummaryEQ applies the EQ predicate on the "ai_summary" field.
func AiSummaryEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldAiSummary, v))
}

// AiSummaryNEQ applies the NEQ predicate on the "ai_summary" field.
func AiSummaryNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldAiSummary, v))
}

// AiSummaryIn applies the In predicate on the "ai_summary" field.
func AiSummaryIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldAiSummary, vs...))
}

// AiSummaryNotIn applies the NotIn predicate on the "ai_summary" field.
func AiSummaryNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldAiSummary, vs...))
}

// AiSummaryGT applies the GT predicate on the "ai_summary" field.
func AiSummaryGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldAiSummary, v))
}

// AiSummaryGTE applies the GTE predicate on the "ai_summary" field.
func AiSummaryGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldAiSummary, v))
}

// AiSummaryLT applies the LT predicate on the "ai_summary" field.
func AiSummaryLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldAiSummary, v))
}

// AiSummaryLTE applies the LTE predicate on the "ai_summary" field.
func AiSummaryLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldAiSummary, v))
}

// AiSummaryContains applies the Contains predicate on the "ai_summary" field.
func AiSummaryContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldAiSummary, v))
}

// AiSummaryHasPrefix applies the HasPrefix predicate on the "ai_summary" field.
func AiSummaryHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldAiSummary, v))
}

// AiSummaryHasSuffix applies the HasSuffix predicate on the "ai_summary" field.
func AiSummaryHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldAiSummary, v))
}

// AiSummaryEqualFold applies the EqualFold predicate on the "ai_summary" field.
func AiSummaryEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldAiSummary, v))
}

// AiSummaryContainsFold applies the ContainsFold predicate on the "ai_summary" field.
func AiSummaryContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldAiSummary, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldError, v))
}

// PushedAtEQ applies the EQ predicate on the "pushed_at" field.
func PushedAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldPushedAt, v))
}

// PushedAtNEQ applies the NEQ predicate on the "pushed_at" field.
func PushedAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldPushedAt, v))
}

// PushedAtIn applies the In predicate on the "pushed_at" field.
func PushedAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldPushedAt, vs...))
}

// PushedAtNotIn applies the NotIn predicate on the "pushed_at" field.
func PushedAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldPushedAt, vs...))
}

// PushedAtGT applies the GT predicate on the "pushed_at" field.
func PushedAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldPushedAt, v))
}

// PushedAtGTE applies the GTE predicate on the "pushed_at" field.
func PushedAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldPushedAt, v))
}

// PushedAtLT applies the LT predicate on the "pushed_at" field.
func PushedAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldPushedAt, v))
}

// PushedAtLTE applies the LTE predicate on the "pushed_at" field.
func PushedAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldPushedAt, v))
}

// PushedAtIsNil applies the IsNil predicate on the "pushed_at" field.
func PushedAtIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldPushedAt))
}

// PushedAtNotNil applies the NotNil predicate on the "pushed_at" field.
func PushedAtNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldPushedAt))
}

// LastPushErrorEQ applies the EQ predicate on the "last_push_error" field.
func LastPushErrorEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldLastPushError, v))
}

// LastPushErrorNEQ applies the NEQ predicate on the "last_push_error" field.
func LastPushErrorNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldLastPushError, v))
}

// LastPushErrorIn applies the In predicate on the "last_push_error" field.
func LastPushErrorIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldLastPushError, vs...))
}

// LastPushErrorNotIn applies the NotIn predicate on the "last_push_error" field.
func LastPushErrorNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldLastPushError, vs...))
}

// LastPushErrorGT applies the GT predicate on the "last_push_error" field.
func LastPushErrorGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldLastPushError, v))
}

// LastPushErrorGTE applies the GTE predicate on the "last_push_error" field.
func LastPushErrorGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldLastPushError, v))
}

// LastPushErrorLT applies the LT predicate on the "last_push_error" field.
func LastPushErrorLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldLastPushError, v))
}

// LastPushErrorLTE applies the LTE predicate on the "last_push_error" field.
func LastPushErrorLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldLastPushError, v))
}

// LastPushErrorContains applies the Contains predicate on the "last_push_error" field.
func LastPushErrorContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldLastPushError, v))
}

// LastPushErrorHasPrefix applies the HasPrefix predicate on the "last_push_error" field.
func LastPushErrorHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldLastPushError, v))
}

// LastPushErrorHasSuffix applies the HasSuffix predicate on the "last_push_error" field.
func LastPushErrorHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldLastPushError, v))
}

// LastPushErrorEqualFold applies the EqualFold predicate on the "last_push_error" field.
func LastPushErrorEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldLastPushError, v))
}

// LastPushErrorContainsFold applies the ContainsFold predicate on the "last_push_error" field.
func LastPushErrorContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldLastPushError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Report) predicate.Report {
	return predicate.Report(sql.NotPredicates(p))
}
